### ISSUE TITLE
Update the file structure 

### ISSUE THREAD

**Issue by kRHYME7** [RAprogramm/OneDark#8]
Hello sir. It would be great if this repo's file structure will also follow the Hyde branch.
https://github.com/kRHYME7/Hyprdots-gallery

You can use this as a guide.

*We can make a separate branch for hyde for now.

**Comment by RAprogramm** [comment]
Yes,  sir! ) I'll try to make it today evening

**Comment by RAprogramm** [comment]
@kRHYME7 check this out! https://github.com/RAprogramm/OneDark/tree/One-Dark-hyde.
Should i rename branches?

**Comment by kRHYME7** [comment]
Should be fine, themepatcher will let us choose which branch

```  Hyde theme patch "One-Dark" https://github.com/RAprogramm/OneDark/tree/One-Dark-hyde ``` 

![image](https://github.com/RAprogramm/OneDark/assets/53417443/e6a4ac76-972a-4798-9223-c557cf2167ff)


``` Hyde theme patch "One Dark" https://github.com/RAprogramm/OneDark ``` << Without branch

![image](https://github.com/RAprogramm/OneDark/assets/53417443/2195913d-ffda-4fa0-887c-06736e27a72d)


For now, it's fine to have both branches as while we are testing the new hyde implementation.
